### ISSUE TITLE
Option to remove (or add) replay link from output

### ISSUE THREAD

**Issue by nalka0** [FrequentlyMissedDeadlines/cgsubmit#4]
In order to have softer outputs, it would be nice to have an option (either passed as argument when doing `python -m cgsubmit -t token` or set via some kind configuration command) that removes (or adds, depending on what you want the default behaviour to be) the `https://www.codingame.com/replay/{replayId}` part of the output for lost games

**Comment by FrequentlyMissedDeadlines** [comment]
done in release 1.1.0
use --noreplay
