### ISSUE TITLE
Fall Challenge 2023 doesn't have generateSessionFromPuzzlePrettyId query

### ISSUE THREAD

**Issue by pde-bakk** [FrequentlyMissedDeadlines/cgsubmit#7]
As the title says, Fall Challenge 2023 doesn't have generateSessionFromPuzzlePrettyId query.
Where are we supposed to pull the necessary token from?

**Comment by FrequentlyMissedDeadlines** [comment]
hello, thanks for reporting your issue.
you can trigger this call by clicking on "LAST BATTLES" in the game IDE and retrieve your token:
![image](https://github.com/FrequentlyMissedDeadlines/cgsubmit/assets/72335976/86f45f17-c0bb-479f-80bd-f6cf2b8dbe89)

**Comment by pde-bakk** [comment]
Ah, thank you. Could you maybe post this in the README so other people can see this too?
